version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./:/var/www/html"
    container_name: "proyectophp_albert_rene"